general:
  plotstyle: 'bmh'
  exportformat: 'ASCII'
  exportformats:
  - ASCII
  - IgorPro
file:
  name: Bias-Spectroscopy00001.dat
  path: C:/
image:
  cmap: default 
  cmapI: viridis
  cmapdIdV: magma 
  defaultch: Z (m)
  extension: .sxm
spec:
  cmap: default
  defaultch: Current (A)
  defaultchZ: Current (A)
  extension: .dat
grid:
  extension: .3ds
  defaultch: Current (A)
fft:
  cmap: viridis
  level: 20
  window: Hanning
  windows:
  - None
  - Hanning
  - Hamming
  - Blackman
buttons:
  infobox: true
  flatten: true
  plane: false
  index: false
  logplot: false
  legend: true
  average: false
  replace: false
cmaps:
- default
- gray
- viridis
- plasma
- inferno
- magma
- cividis
- cool
- hot
- afmhot
- jet
- bright
- vibrant
- high-contrast
- muted
- medium-contrast
- pale
- dark
- light
- Set1
- Paired
- Dark2
- tab10
- tab20
- gray_r
- viridis_r
- plasma_r
- inferno_r
- magma_r
- cividis_r
- cool_r
- hot_r
- afmhot_r
- jet_r
csets:
- Set1
- Paired
- Dark2
- tab10
- tab20
label:
  Bias calc (V): V (V)
  Current (A): I (A)
  LI Demod 1 X (A): dI / dV (A/V)
  OC D1 Amplitude (m): A (m)
  OC M1 Freq. Shift (Hz): dF (Hz)